### PR TITLE
wrote a data science article

### PR DESCRIPTION
**Pull request by metrosmash**
wrote an article for the data science issue

### CODE REVIEW

**Comment by Favour-dgreat** [comment]
Great Article.
Kindly provide the following details, so we can publish your article:
title: {e.g. Software Developer}
url: {Github URL}
image_url: {URL to a neat headshot image of yourself}

**Comment by metrosmash** [comment]
title: {Machine Learning Engineer}
url: {https://github.com/metrosmash}
image_url: {https://media-exp1.licdn.com/dms/image/D4D35AQEfHcGu3gD7HQ/profile-framedphoto-shrink_800_800/0/1659671834699?e=1666782000&v=beta&t=0qq4nOaoUG7ehzyNECk9rmEeFacLUqCxIF7VsFMN0EQ}

**Comment by Favour-dgreat** [comment]
> title: {Machine Learning Engineer} url: {[https://github.com/metrosmash}](https://github.com/metrosmash%7D) image_url: {[https://media-exp1.licdn.com/dms/image/D4D35AQEfHcGu3gD7HQ/profile-framedphoto-shrink_800_800/0/1659671834699?e=1666782000&v=beta&t=0qq4nOaoUG7ehzyNECk9rmEeFacLUqCxIF7VsFMN0EQ}](https://media-exp1.licdn.com/dms/image/D4D35AQEfHcGu3gD7HQ/profile-framedphoto-shrink_800_800/0/1659671834699?e=1666782000&v=beta&t=0qq4nOaoUG7ehzyNECk9rmEeFacLUqCxIF7VsFMN0EQ%7D)
Screenshot 2022-10-19 at 11 37 58

**Comment by Favour-dgreat** [comment]
> > title: {Machine Learning Engineer} url: {[https://github.com/metrosmash}](https://github.com/metrosmash%7D) image_url: {[https://media-exp1.licdn.com/dms/image/D4D35AQEfHcGu3gD7HQ/profile-framedphoto-shrink_800_800/0/1659671834699?e=1666782000&v=beta&t=0qq4nOaoUG7ehzyNECk9rmEeFacLUqCxIF7VsFMN0EQ}](https://media-exp1.licdn.com/dms/image/D4D35AQEfHcGu3gD7HQ/profile-framedphoto-shrink_800_800/0/1659671834699?e=1666782000&v=beta&t=0qq4nOaoUG7ehzyNECk9rmEeFacLUqCxIF7VsFMN0EQ%7D)
> 
> Screenshot 2022-10-19 at 11 37 58

Please send a clean image of you to my email: adeshinafavour4@gmail.com. I will go ahead and approve this PR Now

**Pull request merged**
